language: node_js
node_js:
  - "stable"
script:
 - npm run build
branches:
  only:
    - development
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project the-dog-project-staging --token $FIREBASE_2020
notifications:
  slack: nuphilosophy:DF9RFkQP3ojK6NqRPY0FOOSk
