language: node_js
node_js:
- stable
script:
- npm run build
install:
- npm install
- npm install -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_2020
  project: "the-dog-project-staging"
  on:
    branch: development
notifications:
  slack: nuphilosophy:DF9RFkQP3ojK6NqRPY0FOOSk
